### PR TITLE
Support multiple data sources

### PR DESCRIPTION
**Pull request by AndLvovSky**
Fixes https://github.com/quarkiverse/quarkus-mybatis/issues/13.
- support configuring of specific data source
- CDI integration

## Support for multiple data sources
You can choose a specific data source for MyBatis mapper using the annotation `@MapperDataSource`.
Query in the next example will be running against data source with name `user`.
If there is no such annotation on the mapper, the default data source will be used.

```java
@Mapper
@MapperDataSource("user")
public interface UserMapper {
  @Select("SELECT * FROM USERS WHERE id = #{id}")
  User getUser(Integer id);
}
```

## Configuring specific data source

```yml
# H2 (Default)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:default
quarkus.mybatis.initial-sql=insert.sql

# Derby
quarkus.datasource.derby.db-kind=derby
quarkus.datasource.derby.jdbc.url=jdbc:derby://localhost:1527/memory:testDB;create=true
quarkus.mybatis.derby.initial-sql=insert-derby.sql
```

## CDI integration
Injects default session factory:

```java
@Inject
SqlSessionFactory sqlSessionFactory;
```

Injects session factory for data source `user`:

```java
@Named("user")
SqlSessionFactory sqlSessionFactory;
```

### CODE REVIEW

**Comment by igor-dmitriev** [comment]
CC @zhfeng @ jchambrin
It is a very valuable change for us, we need to use it in "production". Please review and release ASAP if there no concerns.

**Comment by zhfeng** [comment]
Thanks @AndLvovSky and @igor-dmitriev for the great work ! I'd like to add this feature in the document.

**Comment by zhfeng** [comment]
Well, it looks like the docs has been relevanted with these chages. I will start the new releasing.

**Comment by jchambrin** [comment]
Thanks @AndLvovSky and @igor-dmitriev for implementing this feature. Great work !

**Pull request merged**
