### PR TITLE
Mapper locations support.

### PR DESCRIPTION
**Pull request by y-bowen**
add properties quarkus.mybatis.mapper-locations=mapper,othermapper, and then create the dtd resource file in the redources directory.

### CODE REVIEW

**Comment by zhfeng** [comment]
Thanks @y-bowen for the contribution. These changes look good to me and can you add some unit test for the ```mapper-locations```? and I think the mappers could be also defined in the xml configuration see https://mybatis.org/mybatis-3/configuration.html#mappers. I just wonder the motivation to add ```quarkus.mybatis.mapper-locations```.

**Comment by y-bowen** [comment]
> 



> Thanks @y-bowen for the contribution. These changes look good to me and can you add some unit test for the `mapper-locations`? and I think the mappers could be also defined in the xml configuration see https://mybatis.org/mybatis-3/configuration.html#mappers. I just wonder the motivation to add `quarkus.mybatis.mapper-locations`.

ok , i'll do that.

**Comment by y-bowen** [comment]
> Thanks @y-bowen for the contribution. These changes look good to me and can you add some unit test for the `mapper-locations`? and I think the mappers could be also defined in the xml configuration see https://mybatis.org/mybatis-3/configuration.html#mappers. I just wonder the motivation to add `quarkus.mybatis.mapper-locations`.

Hi @zhfeng , My project have  a large number of XML MAPPER , If i use XML Config, I need to maintain a lot of Mapper Resources in XML Config.   This part of the code is a bit like this https://github.com/mybatis/spring-boot-starter/blob/e7e7c9cc482fa293b4ea0a0377669080daf99d30/mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java#L53

**Comment by zhfeng** [comment]
@y-bowen OK, I understand. So can you check the CI failure and I think it could be something with formating. And then I will merge it if CI passes.

Thanks again !

**Comment by zhfeng** [comment]
@allcontributors please add @y-bowen as contributor.

**Comment by zhfeng** [comment]
@allcontributors please add @y-bowen as a contributor for code.

**Comment by zhfeng** [comment]
Thansk @y-bowen for your contributions !

**Comment by zhfeng** [comment]
@y-bowen I will schdule a new release 1.0.1 in this weekend. Feel free to try when it releases.

**Comment by zhfeng** [comment]
@y-bowen 1.0.1 gets out !

**Pull request merged**
