### PR TITLE
Add all Configuration properties

### PR DESCRIPTION
**Pull request by igor-dmitriev**
https://mybatis.org/mybatis-3/configuration.html#settings

```2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - --------------------------------------------------------
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - MyBatis Configuration properties:
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - cacheEnabled: false
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - lazyLoadingEnabled: true
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - aggressiveLazyLoading: true
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - multipleResultSetsEnabled: false
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - useColumnLabel: false
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - useGeneratedKeys: true
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - autoMappingBehavior: FULL
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - autoMappingUnknownColumnBehavior: NONE
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - defaultExecutorType: SIMPLE
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - defaultStatementTimeout: 3000
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - defaultFetchSize: 50
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - defaultResultSetType: FORWARD_ONLY
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - safeRowBoundsEnabled: true
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - safeResultHandlerEnabled: false
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - mapUnderscoreToCamelCase: true
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - localCacheScope: STATEMENT
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - jdbcTypeForNull: DECIMAL
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - lazyLoadTriggerMethods: [equals, hashCode]
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - defaultScriptingLanguage: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver@4ff5f725
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - callSettersOnNulls: true
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - returnInstanceForEmptyRow: true
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - logPrefix: test
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - logImpl: null
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - proxyFactory: org.apache.ibatis.executor.loader.javassist.JavassistProxyFactory@5170a01
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - vfsImpl: null
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - useActualParamName: false
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - configurationFactory: null
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - shrinkWhitespacesInSql: true
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - defaultSqlProviderType: null
2021-03-16 22:07:54 |  [DEBUG] MyBatisRecorder - --------------------------------------------------------
```

### CODE REVIEW

**Comment by zhfeng** [comment]
Thanks @igor-dmitriev and I am not very sure that all of these properties can work in the native mode. For example, ```defaultScriptingLanguage``` and ```proxyFactory```. Since github workflow has not run the native tests currently, can you check ```mvn -f integration-tests/pom.xml clean verify -Dnative``` is working ?

**Comment by igor-dmitriev** [comment]
@zhfeng sure, will check

**Comment by igor-dmitriev** [comment]
@zhfeng I was able to test it with native image.
I've built an artifact:
```
 ./gradlew clean build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
```
then deployed it to my AWS Lambda and printed out all configuration properties to the console:
Screenshot 2021-03-17 at 11 23 52

**Comment by zhfeng** [comment]
Great job ! Thanks again @igor-dmitriev

**Comment by zhfeng** [comment]
@all-contributors add @igor-dmitriev as code please !

**Comment by zhfeng** [comment]
@all-contributors add @igor-dmitriev as code please !

**Comment by zhfeng** [comment]
@all-contributors add @igor-dmitriev as code please !

**Pull request merged**
